# Use nixpacks for Railway deployment

[phases.setup]
nixPkgs = ["...", "openssl"]

[phases.install]
# Install workspace deps at the repo root
cmd = "npm ci"

[phases.build]
# Build the backend using the workspace script (also builds admin when enabled)
cmd = "npm run railway:build --workspace=backend"

[start]
# Start the backend service on the assigned PORT
cmd = "npm run railway:start --workspace=backend"

[env]
NODE_ENV = "production"
MEDUSA_ADMIN_ONBOARDING_TYPE = "default"
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY = ""
