# Use nixpacks for Railway deployment
[build]
cmd = "npm run railway:build"

[start]
cmd = "npm run railway:start"

[phases.setup]
nixPkgs = ["...", "openssl"]

[env]
NODE_ENV = "production"
MEDUSA_ADMIN_ONBOARDING_TYPE = "default"
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY = ""
